apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app: sample
  creationTimestamp: null
  labels:
    app: sample
  name: sample
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sample
subjects:
- kind: ServiceAccount
  name: sample
