apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app: sample
  creationTimestamp: null
  labels:
    app: sample
  name: sample
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
